#!/usr/bin/env bash
#
# extract-locale-keys.sh
# Extracts every translatable key from addon source and writes a sorted,
# de-duplicated list to Locales/_keys.txt. Covered literals include:
# - the first string passed to EllesmereUI.L(...) / EllesmereUI.Lf(...)
# - the first string passed to DisabledTooltip(...)
# - string literals passed directly to ShowWidgetTooltip(...)
# - string values assigned to tooltip / disabledTooltip config fields
#
# This is the STATIC key list (literals only). Keys passed as variables -- e.g.
# L(cfg.text) -- cannot be seen statically; use the in-game /euiloc harvester for
# the complete runtime set. Together they cover everything.
#
# Usage:  ./.tools/extract-locale-keys.sh        (run from anywhere)
# CI uses this to verify Locales/_keys.txt is current (see locale-check.yml).
#
set -euo pipefail
export LC_ALL=C

# cd to the addon root (parent of .tools/)
cd "$(dirname "$0")/.."

OUT="Locales/_keys.txt"
TMP="$(mktemp)"

grep -rhoE '((EllesmereUI|EUI)\.Lf?\(|DisabledTooltip\(|ShowWidgetTooltip\(|_?disabledTooltip[[:space:]]*=|([^[:alnum:]_]|^)tooltip[[:space:]]*=).*' \
  --include='*.lua' \
  --exclude-dir='Libs' \
  --exclude-dir='Locales' \
  --exclude='EllesmereUI_LocaleDev.lua' \
  . \
  | perl -ne '
      while (/(?:EllesmereUI|EUI)\.Lf?\(\s*(["'\''"])((?:\\.|(?!\1).)*)\1/g) { print "$2\n" }
      while (/(?:EllesmereUI\.)?DisabledTooltip\(\s*(["'\''"])((?:\\.|(?!\1).)*)\1/g) { print "$2\n" }
      while (/ShowWidgetTooltip\([^,\n]*,\s*(["'\''"])((?:\\.|(?!\1).)*)\1\s*(?:[,)]|$)/g) { print "$2\n" }
      while (/\b_?disabledTooltip\s*=\s*(["'\''"])((?:\\.|(?!\1).)*)\1/g) { print "$2\n" }
      while (/(?<!fixed)\btooltip\s*=\s*(["'\''"])((?:\\.|(?!\1).)*)\1/g) { print "$2\n" }
    ' \
  | sort -u > "$TMP"

COUNT="$(wc -l < "$TMP" | tr -d ' ')"

{
  echo "# Auto-generated by .tools/extract-locale-keys.sh -- do not edit by hand."
  echo "# Canonical list of translatable English keys found as string literals"
  echo "# ($COUNT unique). Regenerate after wrapping new strings. Keys passed as"
  echo "# variables are not listed here -- use the in-game /euiloc harvester for"
  echo "# the complete runtime set."
  cat "$TMP"
} > "$OUT"

rm -f "$TMP"
echo "Wrote $COUNT keys to $OUT"
